title: console.blog()
email: erzheng@ctemc.org
description: > #
  This is a yearlong project for Ms. Agazarian's senior English class.
baseurl: "/eng4-blog"
github_username: air-wreck

permalink: /:title/
version: v3.7.7
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include: ['_posts']
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md

theme: jekyll-theme-minimal
