name: Eric's English Blog
description: A class project

baseurl: "/eng4-blog"

permalink: /:title/
version: v3.7.7
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
