title: console.blog()
email: ericzheng@cmu.edu
description: > #
  This is a yearlong project for Ms. Agazarian's senior English class.
github_username: air-wreck

permalink: /:title/
version: v3.7.7
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include: ['_posts']
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - _unfinished/*

